//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int OrderitemID { get; set; }
        public string Productname { get; set; }
        public Nullable<double> height { get; set; }

        public string Weight { get; set; }
        public byte[] Image { get; set; }
        public string SKU { get; set; }
        public string Barcode { get; set; }
        public string AvailableQuantity { get; set; }

        public IEnumerable<tbl_Product> Productdetails { get; set; }
    }
}
