//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Orders
    {
        public int OrderID { get; set; }
        public string Buyer_Name { get; set; }
        public string Buyer_Mobileno { get; set; }
        public string OrderStatus { get; set; }
        public string ShippingAddress { get; set; }
        public string Orderitems { get; set; }
        public Nullable<int> OrderitemID { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public string Email { get; set; }


        public IEnumerable<tbl_Orders> Ordersdetails { get; set; }
    }
}
